import React from 'react';

import * as S from './Pipes.style';

export function Pipes() {
    return (
        <S.Container>
            <S.Grid>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
                <S.Card>
                    <i>Lock</i>
                    <i>Favorite</i>
                    <div>
                        <h2>Title</h2>
                        <span>
                            <span>0</span>
                            Cards
                        </span>
                    </div>
                </S.Card>
            </S.Grid>
        </S.Container>
    );
}